controller_frequency: 2.0 

TrajectoryPlannerROS:
  max_vel_x: 3.0
  min_vel_x: 0.2
  max_vel_y: 0.0 
  min_vel_y: 0.0
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.1
  acc_lim_theta: 1.0
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  holonomic_robot: false
  meter_scoring: true
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.2
